#include<iostream.h>
#include<conio.h>

/*
	Pre-Processor Directives
	#- Pre-Processor
	inlcude
	Directive-Folder- iostream or conio
	iostream: input / output stream/flow of data
	conio: console input / output
*/

void main() {  // main() - Entry Point
	clrscr(); // clear screen
	cout<<"Hello World";    //print the output on output/console screen
//        cin>>   // read user input
	getch(); // get charater
}